### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by chemik-bit**
Readme update, gmail tool documentation (calendly documentation will be updated in next commit), frontend fix @iljamak have a look at the updates :)

### CODE REVIEW

**Comment by filip-michalsky** [comment]
nice!

**Comment by iljamak** [comment]
Everything seems to be good

**Comment by filip-michalsky** [comment]
@iljamak did you:
A) run the unit tests
B) spin up the frontend locally without container
C) spin up front end in docker locally
D) tested all the tools in th PR
E) reviewed the documentation provided and followed it and were able to reproduce results with all of the tools?

Let me know if you did all A thru E?

**Comment by chemik-bit** [comment]
> @iljamak did you: A) run the unit tests B) spin up the frontend locally without container C) spin up front end in docker locally D) tested all the tools in th PR E) reviewed the documentation provided and followed it and were able to reproduce results with all of the tools?
> 
> Let me know if you did all A thru E?

@iljamak I still have a few touchups to finish for perfect implementation. I will let you know when they are done, so you can follow up with this when all is production ready:)

**Comment by iljamak** [comment]
@filip-michalsky 
I runned the test locally and tested functionality of all tools (StripePaymentLink, CalendlyLink, Gmail, Database Search). I've also reviewed the process of gmail app password generation, which describes it the way i was doing it. 
At the moment of writing previous comment, i didnt runned it inside docker container, however i've tested it and it runs correctly.
I have verified all steps from A to E for the last commit

**Comment by filip-michalsky** [comment]
awesome thank you @iljamak 

@chemik-bit pls let us know when this is ready for prime time!

**Pull request merged**
