### PR TITLE
Update run_api.py

### PR DESCRIPTION
**Pull request by sohaibwcws**
in your .env file 

OPENAI_API_KEY=YOURKEY
TWILIO_AUTH_TOKEN=YOUR TOKEN
TWILIO_PHONE_NUMBER=+YOURTWILLIOFROM_NUMBER

Once activated, it initiates a user dialogue. You have the option to enhance it using Google Text-to-Speech for a more lifelike interaction. However, I was disappointed to see that the demo provided by the developer didn't match the content of the GitHub repository. This prompted me to create my own version, which is functional but not perfect.

### CODE REVIEW

**Comment by filip-michalsky** [comment]
@sohaibwcws thanks a lot for your PR!

I am sorry to hear you got disappointed. The SalesGPT repo is meant to be an exemplary repository to help developers build sales agents. The `run_api.py` script is a text-based example server and as such I don't think adding voice to is it is the right place to be. 

Can you please explain why you would want to convert it to a call? And if you insist on adding this example, could you please rename it to something `run_call.py`, write a test and update the PR?

Thanks a lot! 

Filip

**Review by filip-michalsky — CHANGES_REQUESTED** [review]
Great contribution, thank you! To ensure a high quality, please ensure the requested changes are updated and then we can merge this.

**Comment by sohaibwcws** [comment]
> 

Your 

> 

I was genuinely impressed by the video demo you presented. However, I've encountered some difficulty in replicating the same functionality using voice commands. Although I successfully implemented design and functionality using Google Text to Speech and Speech to Text, I've hit a roadblock when attempting to retrieve answers or questions from SalesGPT through voice commands. If you're willing to share the code for the voice-based interaction you demonstrated, I believe it would be greatly appreciated by everyone :)

**Comment by filip-michalsky** [comment]
@sohaibwcws the low-latency streaming infrastructure is a product in of itself and is outside of scope of SalesGPT repo, unfortunately. 

It is currently in Closed Beta at Crusty AI (https://crusty.ai). 

Happy to accept your PR if you please implement the requested changes.

Thanks!

**Comment by sohaibwcws** [comment]
I am very new to GITHUB and dont know how to accept or change, so if you
can please guide me , sorry about that

**Comment by filip-michalsky** [comment]
@sohaibwcws please open a new PR with your changes if you don;t know how to update your current PR, thanks and closing this for now!

**Pull request closed without merging**
