### PR TITLE
Email tool

### PR DESCRIPTION
**Pull request by iljamak**

### CODE REVIEW

**Comment by filip-michalsky** [comment]
@iljamak also you submitted two of the same PRs, can you please clarify which one is which?

Also let's set up best practices that we ALWAYS include description of what is the PR about.

**Review by filip-michalsky — CHANGES_REQUESTED** [review]
Let's set up best practices that we ALWAYS include description of what is the PR about - we have two duplicate PR's now. Also please update changelog and README on what was added.

**Comment by filip-michalsky** [comment]
File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1280, in _aperform_agent_action
    observation = await tool.arun(
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/tools.py", line 492, in arun
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain_core/tools.py", line 449, in arun
    await self._arun(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/usr/local/lib/python3.11/site-packages/langchain_core/tools.py", line 591, in _arun
    return await run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 493, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/tools.py", line 566, in _run
    else self.func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/salesgpt/tools.py", line 212, in send_email_tool
    result = send_email_with_gmail(email_details)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_email_with_gmail() missing 1 required positional argument: 'recipient_email'

**Comment by filip-michalsky** [comment]
@iljamak Please add a test to the test suite for the email tool.

**Comment by filip-michalsky** [comment]
@iljamak are we all set here?

**Comment by filip-michalsky** [comment]
@chemik-bit can you please do a PR review

**Comment by chemik-bit** [comment]
@iljamak After updates all good on my side! Good work!

**Comment by filip-michalsky** [comment]
Awesome, great job @iljamak !

**Pull request merged**
